apiVersion: benchflow.io/v1alpha1
kind: DeploymentProfile
metadata:
  name: mooncake-embedded-cpu-predeployed
spec:
  platform: rhoai
  mode: distributed-default
  platform_version: RHOAI-3.5.0-ea.2
  platform_channel: beta
  endpoint_path: /v1/models
  model_storage:
    pvc_name: models-storage
    cache_dir: /models
  runtime:
    image: vllm/vllm-openai:v0.26.0
    replicas: 1
    tensor_parallelism: 2
    env:
      USER: benchflow
      PYTHONHASHSEED: "0"
      MOONCAKE_CONFIG_PATH: /models/models/mooncake_config.json
    vllm_args:
      - --max-model-len=8192
      - --kv-transfer-config={"kv_connector":"MooncakeStoreConnector","kv_role":"kv_both"}
      - --trust-remote-code
      - --no-enable-log-requests
      - --enable-prefix-caching
      - --kv-cache-metrics
      - --kv-cache-metrics-sample=0.01
  options:
    enable_auth: false
    startup_probe:
      failureThreshold: 180
