apiVersion: benchflow.io/v1alpha1
kind: DeploymentProfile
metadata:
  name: llm-d-precise-prefix-cache-routing-gateway-cpu-offloading
spec:
  platform: llm-d
  mode: precise-prefix-cache
  repo_url: https://github.com/llm-d/llm-d.git
  repo_ref: v0.8.0
  gateway: istio
  endpoint_path: /v1/models
  model_storage:
    pvc_name: models-storage
    cache_dir: /models
    mount_path: /model-cache
  runtime:
    replicas: 8
    tensor_parallelism: 2
    env:
      USER: benchflow
    vllm_args:
      - --gpu-memory-utilization=0.64
      - --enable-prefix-caching
      - --kv-transfer-config={"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"cpu_bytes_to_use":34359738368}}
  options:
    epp_config: |
      apiVersion: llm-d.ai/v1alpha1
      kind: EndpointPickerConfig
      plugins:
        - type: token-producer
          parameters:
            modelName: {{ model_name }}
            vllm:
              url: "http://{{ release_name }}-render:8000"
        - type: endpoint-notification-source
        - type: precise-prefix-cache-producer
          parameters:
            tokenProcessorConfig:
              blockSize: 1088
            speculativeIndexing: true
            indexerConfig:
              kvBlockIndexConfig:
                enableMetrics: true
            kvEventsConfig:
              topicFilter: "kv@"
              concurrency: 8
              discoverPods: true
              podDiscoveryConfig:
                socketPort: 5556
        - type: prefix-cache-scorer
          parameters:
            prefixMatchInfoProducerName: precise-prefix-cache-producer
        - type: kv-cache-utilization-scorer
        - type: queue-scorer
        - type: no-hit-lru-scorer
          parameters:
            prefixMatchInfoProducerName: precise-prefix-cache-producer
      dataLayer:
        sources:
          - pluginRef: endpoint-notification-source
            extractors:
              - pluginRef: precise-prefix-cache-producer
      schedulingProfiles:
        - name: default
          plugins:
            - pluginRef: kv-cache-utilization-scorer
              weight: 2.0
            - pluginRef: queue-scorer
              weight: 2.0
            - pluginRef: prefix-cache-scorer
              weight: 3.0
            - pluginRef: no-hit-lru-scorer
              weight: 2.0
