apiVersion: benchflow.io/v1alpha1
kind: DeploymentProfile
metadata:
  name: llm-d-storage-offloading
spec:
  platform: llm-d
  mode: inference-scheduling
  repo_url: https://github.com/llm-d/llm-d.git
  repo_ref: v0.7.0
  gateway: standalone
  endpoint_path: /v1/models
  scheduler_image: quay.io/rh-ee-aperdomo/llm-d-inference-scheduler:v0.8.0-storage-index
  model_storage:
    pvc_name: models-storage
    cache_dir: /models
    mount_path: /model-cache
  runtime:
    image: quay.io/rh-ee-aperdomo/llmd-fs-backend:storage-index
    replicas: 4
    tensor_parallelism: 2
    env:
      STORAGE_LOG_LEVEL: debug
    vllm_args:
      - --gpu-memory-utilization=0.85
      - --enable-chunked-prefill
      - --enable-prefix-caching
      - --block-size=64
      - --trust-remote-code
      - --kv-transfer-config={"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"spec_name":"SharedStorageOffloadingSpec","spec_module_path":"llmd_fs_backend.spec","shared_storage_path":"/mnt/files-storage/kv-cache/","block_size":256,"threads_per_gpu":"64","enable_events":true,"storage_events_endpoint":"tcp://*:5559"}}
      - --distributed_executor_backend=mp
  options:
    storage_offloading:
      pvc_name: llm-d-storage-offloading-cache
      storage_class: nfs-rwx
      size: 2500Gi
      access_mode: ReadWriteMany
      mount_path: /mnt/files-storage
      storage_events_port: 5559
    epp_config: |
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
      - type: single-profile-handler
      - type: prefix-cache-scorer
        parameters:
          mode: cache_tracking
          tokenProcessorConfig:
            blockSizeTokens: 64
            hashSeed: "42"
          indexerConfig:
            storageIndexConfig:
              enabled: true
              filterCapacity: 10000000
            kvCacheBackendConfigs:
            - name: gpu
              weight: 1.0
            - name: cpu
              weight: 0.8
          kvEventsConfig:
            topicFilter: kv@
            concurrency: 8
            engineType: vllm
            discoverPods: true
            podDiscoveryConfig:
              podLabelSelector: "benchflow.io/release={{ release_name }}"
              podNamespace: "{{ namespace }}"
              socketPort: {{ storage_offloading.storage_events_port }}
      - type: queue-scorer
      - type: max-score-picker
      schedulingProfiles:
      - name: default
        plugins:
        - pluginRef: prefix-cache-scorer
          weight: 3.0
        - pluginRef: queue-scorer
          weight: 1.0
        - pluginRef: max-score-picker
